"use client"

export * from "./utils"
export {
	addDay,
	addMonth,
	addYear,
	calculateAverage,
	calculateTotalSum,
	capitalize,
	convertDate,
	convertDateShort,
	convertPrice,
	convertToEmail,
	convertYoutube,
	deleteDuplicates,
	detectLanguage,
	disableScroll,
	enableScroll,
	filterObject,
	formatDate,
	formatHour,
	generateNumbers,
	getFirstName,
	getInitials,
	getLastName,
	getNextDay,
	getPercentage,
	getRandom,
	getRandomAvatar,
	getRandomDate,
	getRandomNumber,
	getRandomString,
	getRandomTime,
	getTimeNow,
	getToday,
	getTomorrow,
	getYesterday,
	hexToRgb,
	emailRegex,
	passwordRegex,
	rgbToHex,
	scrollToTop,
	slugify,
	sortByFrequency,
	stringifyPx,
	toCamelCase,
	toConstantCase,
	toDotCase,
	toKebabCase,
	toPascalCase,
	toPathCase,
	toSentenceCase,
	toSnakeCase,
	toTitleCase,
	unslugify,
	uuid,
} from "@julseb-lib/utils"

export * from "./hooks"
export * from "./Variables"
export * from "./context"

export * from "./components/Text"
/* Prepend here - DO NOT REMOVE */
