/*=============================================== Variables ===============================================*/

/*====================== Colors ======================*/

export enum COLORS_LIGHT {
    BLACK = "var(--color-black)",
    WHITE = "var(--color-white)",
    GRAY_50 = "var(--color-light-gray-50)",
    GRAY_100 = "var(--color-light-gray-100)",
    GRAY_200 = "var(--color-light-gray-200)",
    GRAY_300 = "var(--color-light-gray-300)",
    GRAY_400 = "var(--color-light-gray-400)",
    GRAY_500 = "var(--color-light-gray-500)",
    GRAY_600 = "var(--color-light-gray-600)",
    GRAY_700 = "var(--color-light-gray-700)",
    GRAY_800 = "var(--color-light-gray-800)",
    GRAY_900 = "var(--color-light-gray-900)",
    PRIMARY_50 = "var(--color-light-primary-50)",
    PRIMARY_100 = "var(--color-light-primary-100)",
    PRIMARY_200 = "var(--color-light-primary-200)",
    PRIMARY_300 = "var(--color-light-primary-300)",
    PRIMARY_400 = "var(--color-light-primary-400)",
    PRIMARY_500 = "var(--color-light-primary-500)",
    PRIMARY_600 = "var(--color-light-primary-600)",
    PRIMARY_700 = "var(--color-light-primary-700)",
    PRIMARY_800 = "var(--color-light-primary-800)",
    PRIMARY_900 = "var(--color-light-primary-900)",
    SECONDARY_50 = "var(--color-light-secondary-50)",
    SECONDARY_100 = "var(--color-light-secondary-100)",
    SECONDARY_200 = "var(--color-light-secondary-200)",
    SECONDARY_300 = "var(--color-light-secondary-300)",
    SECONDARY_400 = "var(--color-light-secondary-400)",
    SECONDARY_500 = "var(--color-light-secondary-500)",
    SECONDARY_600 = "var(--color-light-secondary-600)",
    SECONDARY_700 = "var(--color-light-secondary-700)",
    SECONDARY_800 = "var(--color-light-secondary-800)",
    SECONDARY_900 = "var(--color-light-secondary-900)",
    SUCCESS_50 = "var(--color-light-success-50)",
    SUCCESS_100 = "var(--color-light-success-100)",
    SUCCESS_200 = "var(--color-light-success-200)",
    SUCCESS_300 = "var(--color-light-success-300)",
    SUCCESS_400 = "var(--color-light-success-400)",
    SUCCESS_500 = "var(--color-light-success-500)",
    SUCCESS_600 = "var(--color-light-success-600)",
    SUCCESS_700 = "var(--color-light-success-700)",
    SUCCESS_800 = "var(--color-light-success-800)",
    SUCCESS_900 = "var(--color-light-success-900)",
    DANGER_50 = "var(--color-light-danger-50)",
    DANGER_100 = "var(--color-light-danger-100)",
    DANGER_200 = "var(--color-light-danger-200)",
    DANGER_300 = "var(--color-light-danger-300)",
    DANGER_400 = "var(--color-light-danger-400)",
    DANGER_500 = "var(--color-light-danger-500)",
    DANGER_600 = "var(--color-light-danger-600)",
    DANGER_700 = "var(--color-light-danger-700)",
    DANGER_800 = "var(--color-light-danger-800)",
    DANGER_900 = "var(--color-light-danger-900)",
    WARNING_50 = "var(--color-light-warning-50)",
    WARNING_100 = "var(--color-light-warning-100)",
    WARNING_200 = "var(--color-light-warning-200)",
    WARNING_300 = "var(--color-light-warning-300)",
    WARNING_400 = "var(--color-light-warning-400)",
    WARNING_500 = "var(--color-light-warning-500)",
    WARNING_600 = "var(--color-light-warning-600)",
    WARNING_700 = "var(--color-light-warning-700)",
    WARNING_800 = "var(--color-light-warning-800)",
    WARNING_900 = "var(--color-light-warning-900)",
    BACKGROUND = "var(--color-light-background)",
    FONT = "var(--color-light-font)",
    LINK_FONT_DEFAULT = "var(--color-light-link-font-default)",
    LINK_FONT_HOVER = "var(--color-light-link-font-hover)",
    LINK_FONT_ACTIVE = "var(--color-light-link-font-active)",
    LINK_BACKGROUND_DEFAULT = "var(--color-light-link-background-default)",
    LINK_BACKGROUND_HOVER = "var(--color-light-link-background-hover)",
    LINK_BACKGROUND_ACTIVE = "var(--color-light-link-background-active)",
    FONT_GHOST_DEFAULT = "var(--color-light-font-ghost-default)",
    FONT_GHOST_HOVER = "var(--color-light-font-ghost-hover)",
    FONT_GHOST_ACTIVE = "var(--color-light-font-ghost-active)",
    BACKGROUND_GHOST_DEFAULT = "var(--color-light-background-ghost-default)",
    BACKGROUND_GHOST_HOVER = "var(--color-light-background-ghost-hover)",
    BACKGROUND_GHOST_ACTIVE = "var(--color-light-background-ghost-active)",
}

export enum COLORS_DARK {
    BLACK = "var(--color-black)",
    WHITE = "var(--color-white)",
    GRAY_50 = "var(--color-dark-gray-50)",
    GRAY_100 = "var(--color-dark-gray-100)",
    GRAY_200 = "var(--color-dark-gray-200)",
    GRAY_300 = "var(--color-dark-gray-300)",
    GRAY_400 = "var(--color-dark-gray-400)",
    GRAY_500 = "var(--color-dark-gray-500)",
    GRAY_600 = "var(--color-dark-gray-600)",
    GRAY_700 = "var(--color-dark-gray-700)",
    GRAY_800 = "var(--color-dark-gray-800)",
    GRAY_900 = "var(--color-dark-gray-900)",
    PRIMARY_50 = "var(--color-dark-primary-50)",
    PRIMARY_100 = "var(--color-dark-primary-100)",
    PRIMARY_200 = "var(--color-dark-primary-200)",
    PRIMARY_300 = "var(--color-dark-primary-300)",
    PRIMARY_400 = "var(--color-dark-primary-400)",
    PRIMARY_500 = "var(--color-dark-primary-500)",
    PRIMARY_600 = "var(--color-dark-primary-600)",
    PRIMARY_700 = "var(--color-dark-primary-700)",
    PRIMARY_800 = "var(--color-dark-primary-800)",
    PRIMARY_900 = "var(--color-dark-primary-900)",
    SECONDARY_50 = "var(--color-dark-secondary-50)",
    SECONDARY_100 = "var(--color-dark-secondary-100)",
    SECONDARY_200 = "var(--color-dark-secondary-200)",
    SECONDARY_300 = "var(--color-dark-secondary-300)",
    SECONDARY_400 = "var(--color-dark-secondary-400)",
    SECONDARY_500 = "var(--color-dark-secondary-500)",
    SECONDARY_600 = "var(--color-dark-secondary-600)",
    SECONDARY_700 = "var(--color-dark-secondary-700)",
    SECONDARY_800 = "var(--color-dark-secondary-800)",
    SECONDARY_900 = "var(--color-dark-secondary-900)",
    SUCCESS_50 = "var(--color-dark-success-50)",
    SUCCESS_100 = "var(--color-dark-success-100)",
    SUCCESS_200 = "var(--color-dark-success-200)",
    SUCCESS_300 = "var(--color-dark-success-300)",
    SUCCESS_400 = "var(--color-dark-success-400)",
    SUCCESS_500 = "var(--color-dark-success-500)",
    SUCCESS_600 = "var(--color-dark-success-600)",
    SUCCESS_700 = "var(--color-dark-success-700)",
    SUCCESS_800 = "var(--color-dark-success-800)",
    SUCCESS_900 = "var(--color-dark-success-900)",
    DANGER_50 = "var(--color-dark-danger-50)",
    DANGER_100 = "var(--color-dark-danger-100)",
    DANGER_200 = "var(--color-dark-danger-200)",
    DANGER_300 = "var(--color-dark-danger-300)",
    DANGER_400 = "var(--color-dark-danger-400)",
    DANGER_500 = "var(--color-dark-danger-500)",
    DANGER_600 = "var(--color-dark-danger-600)",
    DANGER_700 = "var(--color-dark-danger-700)",
    DANGER_800 = "var(--color-dark-danger-800)",
    DANGER_900 = "var(--color-dark-danger-900)",
    WARNING_50 = "var(--color-dark-warning-50)",
    WARNING_100 = "var(--color-dark-warning-100)",
    WARNING_200 = "var(--color-dark-warning-200)",
    WARNING_300 = "var(--color-dark-warning-300)",
    WARNING_400 = "var(--color-dark-warning-400)",
    WARNING_500 = "var(--color-dark-warning-500)",
    WARNING_600 = "var(--color-dark-warning-600)",
    WARNING_700 = "var(--color-dark-warning-700)",
    WARNING_800 = "var(--color-dark-warning-800)",
    WARNING_900 = "var(--color-dark-warning-900)",
    BACKGROUND = "var(--color-dark-background)",
    FONT = "var(--color-dark-font)",
    LINK_FONT_DEFAULT = "var(--color-dark-link-font-default)",
    LINK_FONT_HOVER = "var(--color-dark-link-font-hover)",
    LINK_FONT_ACTIVE = "var(--color-dark-link-font-active)",
    LINK_BACKGROUND_DEFAULT = "var(--color-dark-link-background-default)",
    LINK_BACKGROUND_HOVER = "var(--color-dark-link-background-hover)",
    LINK_BACKGROUND_ACTIVE = "var(--color-dark-link-background-active)",
    FONT_GHOST_DEFAULT = "var(--color-dark-font-ghost-default)",
    FONT_GHOST_HOVER = "var(--color-dark-font-ghost-hover)",
    FONT_GHOST_ACTIVE = "var(--color-dark-font-ghost-active)",
    BACKGROUND_GHOST_DEFAULT = "var(--color-dark-background-ghost-default)",
    BACKGROUND_GHOST_HOVER = "var(--color-dark-background-ghost-hover)",
    BACKGROUND_GHOST_ACTIVE = "var(--color-dark-background-ghost-active)",
}

// export const COLORS = {
//     light: {
//         BLACK: "var(--color-black)",
//         WHITE: "var(--color-white)",
//         GRAY_50: "var(--color-light-gray-50)",
//         GRAY_100: "var(--color-light-gray-100)",
//         GRAY_200: "var(--color-light-gray-200)",
//         GRAY_300: "var(--color-light-gray-300)",
//         GRAY_400: "var(--color-light-gray-400)",
//         GRAY_500: "var(--color-light-gray-500)",
//         GRAY_600: "var(--color-light-gray-600)",
//         GRAY_700: "var(--color-light-gray-700)",
//         GRAY_800: "var(--color-light-gray-800)",
//         GRAY_900: "var(--color-light-gray-900)",
//         PRIMARY_50: "var(--color-light-primary-50)",
//         PRIMARY_100: "var(--color-light-primary-100)",
//         PRIMARY_200: "var(--color-light-primary-200)",
//         PRIMARY_300: "var(--color-light-primary-300)",
//         PRIMARY_400: "var(--color-light-primary-400)",
//         PRIMARY_500: "var(--color-light-primary-500)",
//         PRIMARY_600: "var(--color-light-primary-600)",
//         PRIMARY_700: "var(--color-light-primary-700)",
//         PRIMARY_800: "var(--color-light-primary-800)",
//         PRIMARY_900: "var(--color-light-primary-900)",
//         SECONDARY_50: "var(--color-light-secondary-50)",
//         SECONDARY_100: "var(--color-light-secondary-100)",
//         SECONDARY_200: "var(--color-light-secondary-200)",
//         SECONDARY_300: "var(--color-light-secondary-300)",
//         SECONDARY_400: "var(--color-light-secondary-400)",
//         SECONDARY_500: "var(--color-light-secondary-500)",
//         SECONDARY_600: "var(--color-light-secondary-600)",
//         SECONDARY_700: "var(--color-light-secondary-700)",
//         SECONDARY_800: "var(--color-light-secondary-800)",
//         SECONDARY_900: "var(--color-light-secondary-900)",
//         SUCCESS_50: "var(--color-light-success-50)",
//         SUCCESS_100: "var(--color-light-success-100)",
//         SUCCESS_200: "var(--color-light-success-200)",
//         SUCCESS_300: "var(--color-light-success-300)",
//         SUCCESS_400: "var(--color-light-success-400)",
//         SUCCESS_500: "var(--color-light-success-500)",
//         SUCCESS_600: "var(--color-light-success-600)",
//         SUCCESS_700: "var(--color-light-success-700)",
//         SUCCESS_800: "var(--color-light-success-800)",
//         SUCCESS_900: "var(--color-light-success-900)",
//         DANGER_50: "var(--color-light-danger-50)",
//         DANGER_100: "var(--color-light-danger-100)",
//         DANGER_200: "var(--color-light-danger-200)",
//         DANGER_300: "var(--color-light-danger-300)",
//         DANGER_400: "var(--color-light-danger-400)",
//         DANGER_500: "var(--color-light-danger-500)",
//         DANGER_600: "var(--color-light-danger-600)",
//         DANGER_700: "var(--color-light-danger-700)",
//         DANGER_800: "var(--color-light-danger-800)",
//         DANGER_900: "var(--color-light-danger-900)",
//         WARNING_50: "var(--color-light-warning-50)",
//         WARNING_100: "var(--color-light-warning-100)",
//         WARNING_200: "var(--color-light-warning-200)",
//         WARNING_300: "var(--color-light-warning-300)",
//         WARNING_400: "var(--color-light-warning-400)",
//         WARNING_500: "var(--color-light-warning-500)",
//         WARNING_600: "var(--color-light-warning-600)",
//         WARNING_700: "var(--color-light-warning-700)",
//         WARNING_800: "var(--color-light-warning-800)",
//         WARNING_900: "var(--color-light-warning-900)",
//         BACKGROUND: "var(--color-light-background)",
//         FONT: "var(--color-light-font)",
//         LINK_FONT_DEFAULT: "var(--color-light-link-font-default)",
//         LINK_FONT_HOVER: "var(--color-light-link-font-hover)",
//         LINK_FONT_ACTIVE: "var(--color-light-link-font-active)",
//         LINK_BACKGROUND_DEFAULT: "var(--color-light-link-background-default)",
//         LINK_BACKGROUND_HOVER: "var(--color-light-link-background-hover)",
//         LINK_BACKGROUND_ACTIVE: "var(--color-light-link-background-active)",
//         FONT_GHOST_DEFAULT: "var(--color-light-font-ghost-default)",
//         FONT_GHOST_HOVER: "var(--color-light-font-ghost-hover)",
//         FONT_GHOST_ACTIVE: "var(--color-light-font-ghost-active)",
//         BACKGROUND_GHOST_DEFAULT: "var(--color-light-background-ghost-default)",
//         BACKGROUND_GHOST_HOVER: "var(--color-light-background-ghost-hover)",
//         BACKGROUND_GHOST_ACTIVE: "var(--color-light-background-ghost-active)",
//     },

//     dark: {
//         BLACK: "var(--color-black)",
//         WHITE: "var(--color-white)",
//         GRAY_50: "var(--color-dark-gray-50)",
//         GRAY_100: "var(--color-dark-gray-100)",
//         GRAY_200: "var(--color-dark-gray-200)",
//         GRAY_300: "var(--color-dark-gray-300)",
//         GRAY_400: "var(--color-dark-gray-400)",
//         GRAY_500: "var(--color-dark-gray-500)",
//         GRAY_600: "var(--color-dark-gray-600)",
//         GRAY_700: "var(--color-dark-gray-700)",
//         GRAY_800: "var(--color-dark-gray-800)",
//         GRAY_900: "var(--color-dark-gray-900)",
//         PRIMARY_50: "var(--color-dark-primary-50)",
//         PRIMARY_100: "var(--color-dark-primary-100)",
//         PRIMARY_200: "var(--color-dark-primary-200)",
//         PRIMARY_300: "var(--color-dark-primary-300)",
//         PRIMARY_400: "var(--color-dark-primary-400)",
//         PRIMARY_500: "var(--color-dark-primary-500)",
//         PRIMARY_600: "var(--color-dark-primary-600)",
//         PRIMARY_700: "var(--color-dark-primary-700)",
//         PRIMARY_800: "var(--color-dark-primary-800)",
//         PRIMARY_900: "var(--color-dark-primary-900)",
//         SECONDARY_50: "var(--color-dark-secondary-50)",
//         SECONDARY_100: "var(--color-dark-secondary-100)",
//         SECONDARY_200: "var(--color-dark-secondary-200)",
//         SECONDARY_300: "var(--color-dark-secondary-300)",
//         SECONDARY_400: "var(--color-dark-secondary-400)",
//         SECONDARY_500: "var(--color-dark-secondary-500)",
//         SECONDARY_600: "var(--color-dark-secondary-600)",
//         SECONDARY_700: "var(--color-dark-secondary-700)",
//         SECONDARY_800: "var(--color-dark-secondary-800)",
//         SECONDARY_900: "var(--color-dark-secondary-900)",
//         SUCCESS_50: "var(--color-dark-success-50)",
//         SUCCESS_100: "var(--color-dark-success-100)",
//         SUCCESS_200: "var(--color-dark-success-200)",
//         SUCCESS_300: "var(--color-dark-success-300)",
//         SUCCESS_400: "var(--color-dark-success-400)",
//         SUCCESS_500: "var(--color-dark-success-500)",
//         SUCCESS_600: "var(--color-dark-success-600)",
//         SUCCESS_700: "var(--color-dark-success-700)",
//         SUCCESS_800: "var(--color-dark-success-800)",
//         SUCCESS_900: "var(--color-dark-success-900)",
//         DANGER_50: "var(--color-dark-danger-50)",
//         DANGER_100: "var(--color-dark-danger-100)",
//         DANGER_200: "var(--color-dark-danger-200)",
//         DANGER_300: "var(--color-dark-danger-300)",
//         DANGER_400: "var(--color-dark-danger-400)",
//         DANGER_500: "var(--color-dark-danger-500)",
//         DANGER_600: "var(--color-dark-danger-600)",
//         DANGER_700: "var(--color-dark-danger-700)",
//         DANGER_800: "var(--color-dark-danger-800)",
//         DANGER_900: "var(--color-dark-danger-900)",
//         WARNING_50: "var(--color-dark-warning-50)",
//         WARNING_100: "var(--color-dark-warning-100)",
//         WARNING_200: "var(--color-dark-warning-200)",
//         WARNING_300: "var(--color-dark-warning-300)",
//         WARNING_400: "var(--color-dark-warning-400)",
//         WARNING_500: "var(--color-dark-warning-500)",
//         WARNING_600: "var(--color-dark-warning-600)",
//         WARNING_700: "var(--color-dark-warning-700)",
//         WARNING_800: "var(--color-dark-warning-800)",
//         WARNING_900: "var(--color-dark-warning-900)",
//         BACKGROUND: "var(--color-dark-background)",
//         FONT: "var(--color-dark-font)",
//         LINK_FONT_DEFAULT: "var(--color-dark-link-font-default)",
//         LINK_FONT_HOVER: "var(--color-dark-link-font-hover)",
//         LINK_FONT_ACTIVE: "var(--color-dark-link-font-active)",
//         LINK_BACKGROUND_DEFAULT: "var(--color-dark-link-background-default)",
//         LINK_BACKGROUND_HOVER: "var(--color-dark-link-background-hover)",
//         LINK_BACKGROUND_ACTIVE: "var(--color-dark-link-background-active)",
//         FONT_GHOST_DEFAULT: "var(--color-dark-font-ghost-default)",
//         FONT_GHOST_HOVER: "var(--color-dark-font-ghost-hover)",
//         FONT_GHOST_ACTIVE: "var(--color-dark-font-ghost-active)",
//         BACKGROUND_GHOST_DEFAULT: "var(--color-dark-background-ghost-default)",
//         BACKGROUND_GHOST_HOVER: "var(--color-dark-background-ghost-hover)",
//         BACKGROUND_GHOST_ACTIVE: "var(--color-dark-background-ghost-active)",
//     },
// } as const

/*====================== Overlays ======================*/

export enum OVERLAYS {
    BLACK_50 = "var(--overlay-black-50)",
    BLACK_80 = "var(--overlay-black-80)",
    WHITE_50 = "var(--overlay-white-50)",
    WHITE_80 = "var(--overlay-white-80)",
    GRADIENT_BLACK = "var(--overlay-gradient-black)",
    GRADIENT_WHITE = "var(--overlay-gradient-white)",
}

/*====================== Font families ======================*/

export enum FONT_FAMILIES {
    BODY = "var(--font-family-body)",
    CODE = "var(--font-family-code)",
}

/*====================== Font sizes ======================*/

export enum FONT_SIZES {
    DISPLAY_H1 = "var(--font-size-display-h1)",
    DISPLAY_H2 = "var(--font-size-display-h2)",
    DISPLAY_H3 = "var(--font-size-display-h3)",
    DISPLAY_H4 = "var(--font-size-display-h4)",
    DISPLAY_H5 = "var(--font-size-display-h5)",
    H1 = "var(--font-size-h1)",
    H2 = "var(--font-size-h2)",
    H3 = "var(--font-size-h3)",
    H4 = "var(--font-size-h4)",
    H5 = "var(--font-size-h5)",
    H6 = "var(--font-size-h6)",
    BODY = "var(--font-size-body)",
    SMALL = "var(--font-size-small)",
}

/*====================== Font weights ======================*/

export enum FONT_WEIGHTS {
    REGULAR = "var(--font-weight-regular)",
    BOLD = "var(--font-weight-bold)",
    BLACK = "var(--font-weight-black)",
}

/*====================== Line heights ======================*/

export enum LINE_HEIGHTS {
    BODY = "var(--line-height-body)",
    CODE = "var(--line-height-code)",
}

/*====================== Shadows ======================*/

export enum SHADOWS {
    XXL = "var(--shadow-xxl)",
    XL = "var(--shadow-xl)",
    L = "var(--shadow-l)",
    M = "var(--shadow-m)",
    S = "var(--shadow-s)",
    XS = "var(--shadow-xs)",
}

/*====================== Spacers ======================*/

export enum SPACERS {
    XXL = "var(--spacer-xxl)",
    XL = "var(--spacer-xl)",
    L = "var(--spacer-l)",
    M = "var(--spacer-m)",
    S = "var(--spacer-s)",
    XS = "var(--spacer-xs)",
    XXS = "var(--spacer-xxs)",
}

/*====================== Radiuses ======================*/

export enum RADIUSES {
    XXL = "var(--radius-xxl)",
    XL = "var(--radius-xl)",
    L = "var(--radius-l)",
    M = "var(--radius-m)",
    S = "var(--radius-s)",
    XS = "var(--radius-xs)",
    ROUND = "var(--radius-round)",
    CIRCLE = "var(--radius-circle)",
}

/*====================== Layouts ======================*/

export enum LAYOUTS {
    MAIN_DEFAULT = "var(--main-default)",
    MAIN_LARGE = "var(--main-large)",
    MAIN_FORM = "var(--main-form)",
    MAIN_FULL = "var(--main-full)",
    ASIDE_DEFAULT = "var(--aside-default)",
    ASIDE_SMALL = "var(--aside-small)",
}

/*====================== Transitions ======================*/

export enum TRANSITIONS {
    SHORT = "var(--transition-short)",
    LONG = "var(--transition-long)",
    BEZIER = "var(--transition-bezier)",
}

/*====================== Breakpoints ======================*/

export enum BREAKPOINTS {
    TABLET_LARGE = "(max-width: 1024px)",
    TABLET_SMALL = "(max-width: 768px)",
    MOBILE = "(max-width= 600px)",
    TOUCH = "(hover: none) and (pointer: coarse)",
    HOVER = "(hover: hover)",
}
