import type { LibMaxWidth } from "../types"

export const genMaxWidth: Record<LibMaxWidth, string> = {
	"3xs": "max-w-3xs",
	"2xs": "max-w-2xs",
	xs: "max-w-xs",
	sm: "max-w-sm",
	md: "max-w-md",
	lg: "max-w-lg",
	xl: "max-w-xl",
	"2xl": "max-w-2xl",
	"3xl": "max-w-3xl",
	"4xl": "max-w-4xl",
	"5xl": "max-w-5xl",
	"6xl": "max-w-6xl",
	"7xl": "max-w-7xl",
	none: "max-w-none",
	px: "max-w-px",
	full: "max-w-full",
	dvw: "max-w-dvw",
	dvh: "max-w-dvh",
	lvw: "max-w-lvw",
	lvh: "max-w-lvh",
	svw: "max-w-svw",
	svh: "max-w-svh",
	screen: "max-w-screen",
	min: "max-w-min",
	max: "max-w-max",
	fit: "max-w-fit",
}
