import type { LibFontSizes } from "../types"

export const genFontSize: Record<LibFontSizes, string> = {
	xs: "text-xs",
	sm: "text-sm",
	base: "text-base",
	lg: "text-lg",
	xl: "text-xl",
	"2xl": "text-2xl",
	"3xl": "text-3xl",
	"4xl": "text-4xl",
	"5xl": "text-5xl",
	"6xl": "text-6xl",
	"7xl": "text-7xl",
	"8xl": "text-8xl",
	"9xl": "text-9xl",
	"display-h1": "text-(length:--text-display-h1)",
	"display-h2": "text-(length:--text-display-h2)",
	"display-h3": "text-(length:--text-display-h3)",
	"display-h4": "text-(length:--text-display-h4)",
	"display-h5": "text-(length:--text-display-h5)",
	h1: "text-(length:--text-h1)",
	h2: "text-(length:--text-h2)",
	h3: "text-(length:--text-h3)",
	h4: "text-(length:--text-h4)",
	h5: "text-(length:--text-h5)",
	h6: "text-(length:--text-h6)",
	body: "text-(length:--text-body)",
	small: "text-(length:--text-small)",
}
