import globals from "globals"
import pluginJs from "@eslint/js"
import tseslint from "typescript-eslint"
import pluginReactConfig from "eslint-plugin-react/configs/recommended.js"
import { fixupConfigRules } from "@eslint/compat"

export default [
	{ files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"] },
	{ languageOptions: { parserOptions: { ecmaFeatures: { jsx: true } } } },
	{ languageOptions: { globals: globals.browser } },
	pluginJs.configs.recommended,
	...tseslint.configs.recommended,
	...fixupConfigRules(pluginReactConfig),
	{
		rules: {
			"no-duplicate-imports": "error",
			"react/react-in-jsx-scope": "off",
			"react/no-unescaped-entities": "off",
			"react/display-name": "off",
			"@typescript-eslint/no-explicit-any": "off",
			"no-case-declarations": "off",
			"@typescript-eslint/no-unused-vars": [
				"warn",
				{
					vars: "all",
					args: "after-used",
					ignoreRestSiblings: true,
					destructuredArrayIgnorePattern: "[_]",
				},
			],
			"@typescript-eslint/ban-types": "off",
			"no-constant-binary-expression": "off",
			"@typescript-eslint/ban-ts-comment": "off",
			"no-useless-escape": "off",
			"no-irregular-whitespace": "off",
			"@typescript-eslint/consistent-type-imports": "warn",
			"@typescript-eslint/no-unused-expressions": "warn",
			"@typescript-eslint/no-non-null-asserted-optional-chain": "off",
			"@typescript-eslint/consistent-indexed-object-style": "off",
			"@typescript-eslint/no-inferrable-types": "off",

			"react/function-component-definition": [
				"warn",
				{
					namedComponents: ["arrow-function"],
				},
			],
			"react/jsx-key": "warn",
			"@typescript-eslint/consistent-type-definitions": "off",
			"@typescript-eslint/array-type": [
				"warn",
				{
					default: "generic",
					readonly: "generic",
				},
			],
			"no-restricted-exports": [
				"warn",
				{ restrictDefaultExports: { direct: true } },
			],
			"react/prop-types": "off",
			"no-empty-pattern": "warn",
			"@typescript-eslint/no-empty-object-type": [
				"warn",
				{ allowInterfaces: "with-single-extends" },
			],
			// "prefer-arrow-callback": "warn",
		},
	},
	{
		ignores: [
			"eslint.config.js",
			"cypress.config.ts",
			"plop/*",
			"vite.config.ts",
			"dist",

			// TODO remove
			// "src/pages",
			// "src/data",
			// "src/components",
			// "src/lib/components/Accordion",
			// "src/lib/components/Alert",
			// "src/lib/components/Aside",
			// "src/lib/components/Autocomplete",
			// "src/lib/components/Avatar",
			// "src/lib/components/BackToTop",
			// "src/lib/components/Badge",
			// "src/lib/components/Breadcrumbs",
			// "src/lib/components/Burger",
			// "src/lib/components/Button",
			// "src/lib/components/ButtonGroup",
			// "src/lib/components/ButtonIcon",
			// "src/lib/components/Card",
			// "src/lib/components/CodeContainer",
			// "src/lib/components/ComponentsMixins",
			// "src/lib/components/Cover",
			// "src/lib/components/Datepicker",
			// "src/lib/components/DragList",
			// "src/lib/components/Drawer",
			// "src/lib/components/Dropdown",
			// "src/lib/components/Fade",
			// "src/lib/components/Fallback",
			// "src/lib/components/Fieldset",
			// "src/lib/components/Flexbox",
			// "src/lib/components/Footer",
			// "src/lib/components/Form",
			// "src/lib/components/FullBleed",
			// "src/lib/components/Grid",
			// "src/lib/components/Header",
			// "src/lib/components/Helmet",
			// "src/lib/components/Highlight",
			// "src/lib/components/Hr",
			// "src/lib/components/Icon",
			// "src/lib/components/IconMenu",
			// "src/lib/components/Image",
			// "src/lib/components/Input",
			// "src/lib/components/InputCheck",
			// "src/lib/components/InputComponents",
			// "src/lib/components/InputContainer",
			// "src/lib/components/InputCounter",
			// "src/lib/components/InputImage",
			// "src/lib/components/InputPhone",
			// "src/lib/components/InputPin",
			// "src/lib/components/InputSlider",
			// "src/lib/components/Key",
			// "src/lib/components/LibIcon",
			// "src/lib/components/Linkify",
			// "src/lib/components/ListGroup",
			// "src/lib/components/Loader",
			// "src/lib/components/Main",
			// "src/lib/components/MarkdownContainer",
			// "src/lib/components/MarkdownEditor",
			// "src/lib/components/Masonry",
			// "src/lib/components/Messaging",
			// "src/lib/components/Modal",
			// "src/lib/components/PageLayout",
			// "src/lib/components/PageLoading",
			// "src/lib/components/Pagination",
			// "src/lib/components/Paginator",
			// "src/lib/components/ProgressBar",
			// "src/lib/components/ProgressCircle",
			// "src/lib/components/Rating",
			// "src/lib/components/ResetScroll",
			// "src/lib/components/Section",
			// "src/lib/components/Select",
			// "src/lib/components/Skeleton",
			// "src/lib/components/Slideshow",
			// "src/lib/components/SrOnly",
			// "src/lib/components/Stepper",
			// "src/lib/components/Sticky",
			// "src/lib/components/Table",
			// "src/lib/components/Tabs",
			// "src/lib/components/Tag",
			// "src/lib/components/Text",
			// "src/lib/components/TextIcon",
			// "src/lib/components/Timepicker",
			// "src/lib/components/Toast",
			// "src/lib/components/Tooltip",
			// "src/lib/components/Truncate",
			// "src/lib/components/Video",
			// "src/lib/components/Wrapper",
			// "src/lib/components/Youtube",

			// "src/lib/components",
			// "src/lib/context",
			// "src/lib/hooks",
			// "src/lib/icons",
			// "src/lib/lib-utils",
			// "src/lib/types",
			// "src/lib/utils",
		],
	},
	{
		files: ["src/*"],
	},
]
