import { Meta } from "../../../"
import type {} from "../../../types"
import type { ILibMeta } from "../../../types/components-props"
import type { ComponentPreview } from "../../../../data/components"

export const metaPreview: ComponentPreview<ILibMeta> = {
	name: "Meta",
	component: Meta,
	category: "components",
	import: "Meta",
	additionalImports: null,
	optionalImports: null,
	propsImport: "ILibMeta",
	additionalTypeImports: null,
	extends: null,
	previews: [{ previewTitle: "Default", props: { title: "Wesh" } }],
	props: [
		{
			name: "title",
			type: "string",
			possibleValues: [],
			defaultValue: null,
			description: "Page title for the document and social media.",
			isRequired: true,
		},
		{
			name: "favicon",
			type: "string",
			possibleValues: [],
			defaultValue: null,
			description: "URL path to the favicon icon file.",
			isRequired: false,
		},
		{
			name: "description",
			type: "string",
			possibleValues: [],
			defaultValue: null,
			description: "Page description for SEO and social media.",
			isRequired: false,
		},
		{
			name: "generator",
			type: "string",
			possibleValues: [],
			defaultValue: null,
			description: "Name of the generator used to create the page.",
			isRequired: false,
		},
		{
			name: "keywords",
			type: "Array<string>",
			possibleValues: [],
			defaultValue: null,
			description: "Array of keywords for SEO purposes.",
			isRequired: false,
		},
		{
			name: "author",
			type: "string",
			possibleValues: [],
			defaultValue: null,
			description: "Author name for the page content.",
			isRequired: false,
		},
		{
			name: "authorUrl",
			type: "string",
			possibleValues: [],
			defaultValue: null,
			description: "URL to the author's profile or website.",
			isRequired: false,
		},
		{
			name: "publisher",
			type: "string",
			possibleValues: [],
			defaultValue: null,
			description: "Publisher name for the content.",
			isRequired: false,
		},
		{
			name: "type",
			type: "string",
			possibleValues: [
				"article",
				"book",
				"music.album",
				"music.playlist",
				"music.radio_station",
				"music.song",
				"profile",
				"video.episode",
				"video.movie",
				"video.other",
				"video. tv_show",
				"website",
			],
			defaultValue: "website",
			description: "Open Graph type for social media sharing.",
			isRequired: false,
		},
		{
			name: "cover",
			type: "string",
			possibleValues: [],
			defaultValue: null,
			description: "URL to the cover image for social media sharing.",
			isRequired: false,
		},
		{
			name: "siteName",
			type: "string",
			possibleValues: [],
			defaultValue: null,
			description: "Name of the website or application.",
			isRequired: false,
		},
		{
			name: "language",
			type: "string",
			possibleValues: [],
			defaultValue: null,
			description: "Language locale code (e.g., 'en-US').",
			isRequired: false,
		},
		{
			name: "url",
			type: "string",
			possibleValues: [],
			defaultValue: null,
			description: "Canonical URL of the page.",
			isRequired: false,
		},
		{
			name: "email",
			type: "string",
			possibleValues: [],
			defaultValue: null,
			description: "Contact email address.",
			isRequired: false,
		},
		{
			name: "creator",
			type: "string",
			possibleValues: [],
			defaultValue: null,
			description: "Creator name for the content.",
			isRequired: false,
		},
		{
			name: "manifest",
			type: "string",
			possibleValues: [],
			defaultValue: null,
			description: "URL path to the web app manifest file.",
			isRequired: false,
		},
		{
			name: "category",
			type: "string",
			possibleValues: [],
			defaultValue: null,
			description: "Category classification for the content.",
			isRequired: false,
		},
		{
			name: "twitterCard",
			type: "string",
			possibleValues: ["app", "player", "summary", "summary_large_image"],
			defaultValue: "summary",
			description: "Twitter Card type for social media display.",
			isRequired: false,
		},
	],
}
