import { Hr } from "../../../"
import type { ILibHr } from "../../../types/components-props"
import type { ComponentPreview } from "../../../../data/components"

export const hrPreview: ComponentPreview<ILibHr> = {
	name: "Hr",
	component: Hr,
	category: "components",
	import: "Hr",
	additionalImports: null,
	optionalImports: null,
	propsImport: "ILibHr",
	additionalTypeImports: null,
	extends: ["HTMLHrElement"],
	previews: [
		{ previewTitle: "Default", props: {} },
		{
			previewTitle: "Rounded",
			props: { isRounded: true, className: "h-1" },
		},
	],
	props: [
		{
			name: "maxWidth",
			type: "string",
			possibleValues: [
				"3xs",
				"2xs",
				"xs",
				"sm",
				"md",
				"lg",
				"xl",
				"2xl",
				"3xl",
				"4xl",
				"5xl",
				"6xl",
				"7xl",
				"none",
				"px",
				"full",
				"dvw",
				"dvh",
				"lvw",
				"lvh",
				"svw",
				"svh",
				"screen",
				"min",
				"max",
				"fit",
			],
			defaultValue: "full",
			description: "Maximum width of the hr.",
			isRequired: false,
		},
		{
			name: "color",
			type: "string",
			possibleValues: null,
			defaultValue: "gray-200",
			description: "Background color of the hr.",
			isRequired: false,
		},
		{
			name: "isRounded",
			type: "boolean",
			possibleValues: null,
			defaultValue: null,
			description: "If true, the hr will have fully rounded borders.",
			isRequired: false,
		},
	],
}
