import type { Preview } from "@storybook/react"
import { CodeContainer } from "../src/lib"
import "../src/lib/index.css"

const preview: Preview = {
	parameters: {
		controls: {
			matchers: {
				color: /(background|color)$/i,
				date: /Date$/i,
			},
		},
		options: {
			storySort: {
				method: "",
				order: [
					"Homepage",
					"Getting started",
					"CLI and Boilerplates",
					"Styles/Colors",
					"Styles/Overlays",
					"Styles/Text",
					"Styles/Shadows",
					"Styles/Spacers",
					"Styles/Radiuses",
					"Styles/Theme Provider",
					"Layouts/Wrapper",
					"Layouts/Main",
					"Layouts/Aside",
					"Layouts/Section",
					"Layouts/Grid",
					"Layouts/Flexbox",
					"Components/Icon",
					"Components/Link",
					"Components/Key",
					"Components/Texticon",
					"Components/Highlight",
					"Components/Linkify",
					"Components/Tooltip",
					"Components/Hr",
					"Components/Skeleton",
					"Components/Image",
					"Components/Masonry",
					"Components/Fullbleed",
					"Components/Video",
					"Components/Youtube",
					"Components/Badge",
					"Components/Avatar",
					"Components/Loader",
					"Components/Burger",
					"Components/Button",
					"Components/Buttonicon",
					"Components/Buttongroup",
					"Components/Tag",
					"Components/Truncate",
					"Components/Card",
					"Components/Input",
					"Components/Inputimage",
					"Components/Inputcheck",
					"Components/Inputphone",
					"Components/Inputcounter",
					"Components/Inputslider",
					"Components/Select",
					"Components/Autocomplete",
					"Components/Rating",
					"Components/Inputpin",
					"Components/Datepicker",
					"Components/Timepicker",
					"Components/Fieldset",
					"Components/Form",
					"Components/Listgroup",
					"Components/Breadcrumbs",
					"Components/Accordion",
					"Components/Dropdown",
					"Components/Toast",
					"Components/Alert",
					"Components/Modal",
					"Components/Draglist",
					"Components/Pagination",
					"Components/Paginator",
					"Components/Stepper",
					"Components/Progressbar",
					"Components/Progresscircle",
					"Components/Tabs",
					"Components/Slideshow",
					"Components/Cover",
					"Components/Table",
					"Components/Pageloading",
					"Components/Sticky",
					"Components/Messaging",
					"Components/Markdowneditor",
					"Components/Markdowncontainer",
					"Components/Codecontainer",
					"Components/Fade",
					"Components/Backtotop",
					"Components/Drawer",
					"Components/Header",
					"Components/Iconmenu",
					"Components/Footer",
					"Components/Helmet",
					"Components/Pagelayout",
					"Helpers/Helpers",
					"Helpers/Sronly",
					"Helpers/Variables",
					"Helpers/Mixins",
					"Helpers/Jsutils",
					"Helpers/Optionsmarkdown",
					"Helpers/Hooks",
					"Helpers/Resetscroll",
				],
				locales: "",
			},
		},
		parameters: {
			docs: {
				components: {
					// h1: { component: Text },
					// h2: { component: Text, props: { tag: "h2" } },
					// h3: { component: Text, props: { tag: "h3" } },
					// h4: { component: Text, props: { tag: "h4" } },
					// h5: { component: Text, props: { tag: "h5" } },
					// h6: { component: Text, props: { tag: "h6" } },
					code: { component: CodeContainer },
				},
			},
		},
	},
}

export default preview
