import type { Preview } from "@storybook/react"

import "../src/lib/index.css"

const preview: Preview = {
    parameters: {
        actions: { argTypesRegex: "^on[A-Z].*" },
        controls: {
            matchers: {
                color: /(background|color)$/i,
                date: /Date$/,
            },
        },
        options: {
            storySort: {
                order: [
                    "Home",
                    "Getting started",
                    "Styles",
                    [
                        "Colors",
                        "Overlays",
                        "Text",
                        "Shadows",
                        "Radiuses",
                        "Theme Provider",
                    ],
                    "Layouts",
                    ["Container", "Section", "Spacers", "Grid", "Flexbox"],
                    "Components",
                    [
                        "Icon",
                        "Key",
                        "Text Icon",
                        "Highlight",
                        "Linkify",
                        "Hr",
                        "Skeleton",
                        "Image",
                        "Masonry",
                        "Full Bleed",
                        "Video",
                        "Youtube",
                        "Avatar",
                        "Loader",
                        "Burger",
                        "Button",
                        "Button Icon",
                        "Button Group",
                        "Tag",
                        "Truncate",
                        "Card",
                        "Badge",
                        "Tooltip",
                        "Input",
                        "Input Image",
                        "Input Check",
                        "Input Phone",
                        "Input Counter",
                        "Input Slider",
                        "Select",
                        "Autocomplete",
                        "Rating",
                        "Datepicker",
                        "Timepicker",
                        "Form",
                        "List Group",
                        "Breadcrumbs",
                        "Accordion",
                        "Dropdown",
                        "Toast",
                        "Alert",
                        "Modal",
                        "Pagination",
                        "Paginator",
                        "Stepper",
                        "Progress Bar",
                        "Progress Circle",
                        "Tabs",
                        "Slideshow",
                        "Cover",
                        "Table",
                        "Page Loading",
                        "Sticky",
                        "Messaging",
                        "Markdown Editor",
                        "Markdown Container",
                        "Code Container",
                        "Fade",
                        "Back To Top",
                        "Header",
                        "Icon Menu",
                        "Footer",
                        "Helmet",
                    ],
                    "Helpers",
                    [
                        "Helpers",
                        "Sr Only",
                        "Variables",
                        "Mixins",
                        "Js Utils",
                        "Options Markdown",
                        "Component Props",
                        "Hooks",
                    ],
                ],
            },
        },
    },
}

export default preview
